# Generated by Django 5.2.7 on 2025-10-10 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='producto',
            new_name='proveedor',
        ),
    ]
