# Generated by Django 5.2.7 on 2025-10-11 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_categoria_alter_producto_proveedor'),
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='movimientos.unidadmedida'),
        ),
    ]
