# Generated by Django 5.2 on 2025-10-14

from django.db import migrations, models
import django.utils.timezone
import django.contrib.auth.hashers


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("dni", models.CharField(max_length=20, unique=True)),
                (
                    "rol",
                    models.CharField(
                        max_length=20,
                        choices=[("admin", "Administrador"), ("basico", "Básico")],
                        default="basico",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
    ]
